attitudinal_dimensions:
- lrgen
- eu_position
attitudinal_model:
  N: 2
  random_state: 666
ideological_model:
  check_input: true
  engine: auto
  force_bipartite: true
  force_full_rank: false
  in_degree_threshold: 3
  n_latent_dimensions: 20
  out_degree_threshold: null
  random_state: null
  standardize_mean: true
  standardize_std: false
palette_path: /home/jimena/work/data/some4dem/annotations/${country}/party_palette.yaml
sources_min_followers: 25
sources_min_outdegree: 3
sqlite_db: /home/jimena/work/data/some4dem/some4dem.db