attitudinal_dimensions:
  - lrgen
  - lrecon
  - antielite_salience
  - eu_position
  - immigrate_policy
  - galtan
  - environment
  - eu_political_require
  - enviro_salience
  - eu_salience
  - ethnic_minorities
  - antielite_salience
  - redistribution
  - protectionism
  - urban_rural
  - econ_interven
  - eu_intmark
  - galtan_salience
  - eu_blur
  - lrecon_sd
  - immigrate_policy
  - anti_islam_rhetoric
  - eu_dissent
  - eu_position_sd
  - immigrate_salience
  - deregulation
  - galtan_blur
  - multiculturalism
  - eu_budgets
  - eu_googov_require
  - civlib_laworder
  - regions
  - galtan
  - redist_salience
  - corrupt_salience
  - nationalism
  - lrecon_dissent
  - people_vs_elite
  - eu_cohesion
  - religious_principles
  - lrecon_salience
  - multicult_salience
  - eu_position
  - eu_econ_require
  - lrecon
  - lrgen
  - lrecon_blur
  - members_vs_leadership
  - eu_foreign
  - galtan_dissent
  - spendvtax
  - immigrate_dissent
  - eu_asylum
  - environment
  - multicult_dissent
  - galtan_sd
  - sociallifestyle
attitudinal_model:
  N: 7
  random_state: 666
ideological_model:
  check_input: true
  engine: auto
  force_bipartite: true
  force_full_rank: false
  in_degree_threshold: 3
  n_latent_dimensions: 8
  out_degree_threshold: null
  random_state: null
  standardize_mean: true
  standardize_std: false
sources_min_followers: 25
sources_min_outdegree: 3
sqlite_db: /home/jimena/work/data/some4dem/some4dem.db