ideological_model:
  check_input: true
  engine: auto
  force_bipartite: true
  force_full_rank: false
  in_degree_threshold: 3
  n_latent_dimensions: 9
  out_degree_threshold: null
  random_state: null
  standardize_mean: true
  standardize_std: false
sources_min_followers: 25
sources_min_outdegree: 3
sqlite_db: /home/jimena/work/data/some4dem/some4dem.db