attitudinal_dimensions:
  - lrgen
  - lrecon
  - antielite_salience
  - eu_position
  - immigrate_policy
  - galtan
  - environment
issues:
    - ClimateChange
    - Conservative
    - Corruption
    - Elites
    - Entrepreneur
    - Environment
    - Europe
    - Immigration
    - International
    - Islam
    - Left
    - Right
    - Liberal
    - Patriot
    - People
    - Politicians
    - Populism
    - StartUp
attitudinal_model:
  N: 7
  random_state: 666
ideological_model:
  check_input: true
  engine: auto
  force_bipartite: true
  force_full_rank: false
  in_degree_threshold: 3
  n_latent_dimensions: 8
  out_degree_threshold: null
  random_state: null
  standardize_mean: true
  standardize_std: false
sources_min_followers: 25
sources_min_outdegree: 3
params_db: /home/jimena/work/dev/some4demDB/config.yml
sqlite_db: /home/jimena/work/data/some4dem/dbs/slovenia.db
validation:
  leftright_sentiment_min_rate: 1
  seed: 666