attitudinal:
  gps2019:
    -
  ches2019:
    antielite_salience_vs_environment:
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        Groen:
        - 0
        - 0
        'CD&V':
        - 0
        - 0
        Ecolo:
        - 0
        - 0
        MR:
        - 0
        - 0
        PS:
        - 0
        - 0
        PSC/CDH:
        - 0
        - 0
        PVDA-PTB:
        - 0
        - 0
        SP.A:
        - 0
        - 0
        VB:
        - 0
        - 0
        'Open Vld':
        - 0
        - 0
        N-VA:
        - 0
        - 0
      quantiles: &id002
      - 0
      - 1
    antielite_salience_vs_eu_position:
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        Groen:
        - 0
        - 0
        'CD&V':
        - 0
        - 0
        Ecolo:
        - 0
        - 0
        MR:
        - 0
        - 0
        PS:
        - 0
        - 0
        PSC/CDH:
        - 0
        - 0
        PVDA-PTB:
        - 0
        - 0
        SP.A:
        - 0
        - 0
        VB:
        - 0
        - 0
        'Open Vld':
        - 0
        - 0
        N-VA:
        - 0
        - 0
    antielite_salience_vs_galtan:
      quantiles: *id002
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        Groen:
        - 0
        - 0
        'CD&V':
        - 0
        - 0
        Ecolo:
        - 0
        - 0
        MR:
        - 0
        - 0
        PS:
        - 0
        - 0
        PSC/CDH:
        - 0
        - 0
        PVDA-PTB:
        - 0
        - 0
        SP.A:
        - 0
        - 0
        VB:
        - 0
        - 0
        'Open Vld':
        - 0
        - 0
        N-VA:
        - 0
        - 0
    antielite_salience_vs_immigrate_policy:
      quantiles: *id002
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        Groen:
        - 0
        - 0
        'CD&V':
        - 0
        - 0
        Ecolo:
        - 0
        - 0
        MR:
        - 0
        - 0
        PS:
        - 0
        - 0
        PSC/CDH:
        - 0
        - 0
        PVDA-PTB:
        - 0
        - 0
        SP.A:
        - 0
        - 0
        VB:
        - 0
        - 0
        'Open Vld':
        - 0
        - 0
        N-VA:
        - 0
        - 0
    eu_position_vs_environment:
      quantiles: *id002
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        Groen:
        - 0
        - 0
        'CD&V':
        - 0
        - 0
        Ecolo:
        - 0
        - 0
        MR:
        - 0
        - 0
        PS:
        - 0
        - 0
        PSC/CDH:
        - 0
        - 0
        PVDA-PTB:
        - 0
        - 0
        SP.A:
        - 0
        - 0
        VB:
        - 0
        - 0
        'Open Vld':
        - 0
        - 0
        N-VA:
        - 0
        - 0
    eu_position_vs_galtan:
      quantiles: *id002
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        Groen:
        - 0
        - 0
        'CD&V':
        - 0
        - 0
        Ecolo:
        - 0
        - 0
        MR:
        - 0
        - 0
        PS:
        - 0
        - 0
        PSC/CDH:
        - 0
        - 0
        PVDA-PTB:
        - 0
        - 0
        SP.A:
        - 0
        - 0
        VB:
        - 0
        - 0
        'Open Vld':
        - 0
        - 0
        N-VA:
        - 0
        - 0
    eu_position_vs_immigrate_policy:
      quantiles: *id002
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        Groen:
        - 0
        - 0
        'CD&V':
        - 0
        - 0
        Ecolo:
        - 0
        - 0
        MR:
        - 0
        - 0
        PS:
        - 0
        - 0
        PSC/CDH:
        - 0
        - 0
        PVDA-PTB:
        - 0
        - 0
        SP.A:
        - 0
        - 0
        VB:
        - 0
        - 0
        'Open Vld':
        - 0
        - 0
        N-VA:
        - 0
        - 0
    galtan_vs_environment:
      quantiles: *id002
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        Groen:
        - 0
        - 0
        'CD&V':
        - 0
        - 0
        Ecolo:
        - 0
        - 0
        MR:
        - 0
        - 0
        PS:
        - 0
        - 0
        PSC/CDH:
        - 0
        - 0
        PVDA-PTB:
        - 0
        - 0
        SP.A:
        - 0
        - 0
        VB:
        - 0
        - 0
        'Open Vld':
        - 0
        - 0
        N-VA:
        - 0
        - 0
    immigrate_policy_vs_environment:
      quantiles: *id002
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        Groen:
        - 0
        - 0
        'CD&V':
        - 0
        - 0
        Ecolo:
        - 0
        - 0
        MR:
        - 0
        - 0
        PS:
        - 0
        - 0
        PSC/CDH:
        - 0
        - 0
        PVDA-PTB:
        - 0
        - 0
        SP.A:
        - 0
        - 0
        VB:
        - 0
        - 0
        'Open Vld':
        - 0
        - 0
        N-VA:
        - 0
        - 0
    immigrate_policy_vs_galtan:
      quantiles: *id002
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        Groen:
        - 0
        - 0
        'CD&V':
        - 0
        - 0
        Ecolo:
        - 0
        - 0
        MR:
        - 0
        - 0
        PS:
        - 0
        - 0
        PSC/CDH:
        - 0
        - 0
        PVDA-PTB:
        - 0
        - 0
        SP.A:
        - 0
        - 0
        VB:
        - 0
        - 0
        'Open Vld':
        - 0
        - 0
        N-VA:
        - 0
        - 0
    lrecon_vs_antielite_salience:
      quantiles: *id002
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        Groen:
        - 0
        - 0
        'CD&V':
        - 0
        - 0
        Ecolo:
        - 0
        - 0
        MR:
        - 0
        - 0
        PS:
        - 0
        - 0
        PSC/CDH:
        - 0
        - 0
        PVDA-PTB:
        - 0
        - 0
        SP.A:
        - 0
        - 0
        VB:
        - 0
        - 0
        'Open Vld':
        - 0
        - 0
        N-VA:
        - 0
        - 0
    lrecon_vs_environment:
      quantiles: *id002
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        Groen:
        - 0
        - 0
        'CD&V':
        - 0
        - 0
        Ecolo:
        - 0
        - 0
        MR:
        - 0
        - 0
        PS:
        - 0
        - 0
        PSC/CDH:
        - 0
        - 0
        PVDA-PTB:
        - 0
        - 0
        SP.A:
        - 0
        - 0
        VB:
        - 0
        - 0
        'Open Vld':
        - 0
        - 0
        N-VA:
        - 0
        - 0
    lrecon_vs_eu_position:
      quantiles: *id002
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        Groen:
        - 0
        - 0
        'CD&V':
        - 0
        - 0
        Ecolo:
        - 0
        - 0
        MR:
        - 0
        - 0
        PS:
        - 0
        - 0
        PSC/CDH:
        - 0
        - 0
        PVDA-PTB:
        - 0
        - 0
        SP.A:
        - 0
        - 0
        VB:
        - 0
        - 0
        'Open Vld':
        - 0
        - 0
        N-VA:
        - 0
        - 0
    lrecon_vs_galtan:
      quantiles: *id002
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        Groen:
        - 0
        - 0
        'CD&V':
        - 0
        - 0
        Ecolo:
        - 0
        - 0
        MR:
        - 0
        - 0
        PS:
        - 0
        - 0
        PSC/CDH:
        - 0
        - 0
        PVDA-PTB:
        - 0
        - 0
        SP.A:
        - 0
        - 0
        VB:
        - 0
        - 0
        'Open Vld':
        - 0
        - 0
        N-VA:
        - 0
        - 0
    lrecon_vs_immigrate_policy:
      quantiles: *id002
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        Groen:
        - 0
        - 0
        'CD&V':
        - 0
        - 0
        Ecolo:
        - 0
        - 0
        MR:
        - 0
        - 0
        PS:
        - 0
        - 0
        PSC/CDH:
        - 0
        - 0
        PVDA-PTB:
        - 0
        - 0
        SP.A:
        - 0
        - 0
        VB:
        - 0
        - 0
        'Open Vld':
        - 0
        - 0
        N-VA:
        - 0
        - 0
    lrgen_vs_antielite_salience:
      quantiles: *id002
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        Groen:
        - 0
        - 0
        'CD&V':
        - 0
        - 0
        Ecolo:
        - 0
        - 0
        MR:
        - 0
        - 0
        PS:
        - 0
        - 0
        PSC/CDH:
        - 0
        - 0
        PVDA-PTB:
        - 0
        - 0
        SP.A:
        - 0
        - 0
        VB:
        - 0
        - 0
        'Open Vld':
        - 0
        - 0
        N-VA:
        - 0
        - 0
    lrgen_vs_environment:
      quantiles: *id002
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        Groen:
        - 0
        - 0
        'CD&V':
        - 0
        - 0
        Ecolo:
        - 0
        - 0
        MR:
        - 0
        - 0
        PS:
        - 0
        - 0
        PSC/CDH:
        - 0
        - 0
        PVDA-PTB:
        - 0
        - 0
        SP.A:
        - 0
        - 0
        VB:
        - 0
        - 0
        'Open Vld':
        - 0
        - 0
        N-VA:
        - 0
        - 0
    lrgen_vs_eu_position:
      quantiles: *id002
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        Groen:
        - 0
        - 0
        'CD&V':
        - 0
        - 0
        Ecolo:
        - 0
        - 0
        MR:
        - 0
        - 0
        PS:
        - 0
        - 0
        PSC/CDH:
        - 0
        - 0
        PVDA-PTB:
        - 0
        - 0
        SP.A:
        - 0
        - 0
        VB:
        - 0
        - 0
        'Open Vld':
        - 0
        - 0
        N-VA:
        - 0
        - 0
    lrgen_vs_galtan:
      quantiles: *id002
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        Groen:
        - 0
        - 0
        'CD&V':
        - 0
        - 0
        Ecolo:
        - 0
        - 0
        MR:
        - 0
        - 0
        PS:
        - 0
        - 0
        PSC/CDH:
        - 0
        - 0
        PVDA-PTB:
        - 0
        - 0
        SP.A:
        - 0
        - 0
        VB:
        - 0
        - 0
        'Open Vld':
        - 0
        - 0
        N-VA:
        - 0
        - 0
    lrgen_vs_immigrate_policy:
      quantiles: *id002
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        Groen:
        - 0
        - 0
        'CD&V':
        - 0
        - 0
        Ecolo:
        - 0
        - 0
        MR:
        - 0
        - 0
        PS:
        - 0
        - 0
        PSC/CDH:
        - 0
        - 0
        PVDA-PTB:
        - 0
        - 0
        SP.A:
        - 0
        - 0
        VB:
        - 0
        - 0
        'Open Vld':
        - 0
        - 0
        N-VA:
        - 0
        - 0
    lrgen_vs_lrecon:
      quantiles: *id002
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        Groen:
        - 0
        - 0
        'CD&V':
        - 0
        - 0
        Ecolo:
        - 0
        - 0
        MR:
        - 0
        - 0
        PS:
        - 0
        - 0
        PVDA-PTB:
        - 0
        - 0
        SP.A:
        - 0
        - 0
        VB:
        - 0
        - 0
        'Open Vld':
        - 0
        - 0
        N-VA:
        - 0
        - 0
ideological:
  cbar_rect:
  - 0.15
  - 0.35
  - 0.03
  - 0.45
  legend_loc: upper right
  limits:
    x:
    - -2
    - 4
    y:
    - -2
    - 4
  nudges:
    Groen:
    - 0.25
    - -0.25
    'CD&V':
    - -0.7
    - 0
    Ecolo:
    - 0.2
    - -0.3
    MR:
    - -0.75
    - 0.15
    PS:
    - 0.3
    - -0.2
    PVDA-PTB:
    - 0
    - -0.4
    SP.A:
    - -0.8
    - -0.4
    VB:
    - 0.2
    - 0
    'Open Vld':
    - -1.6
    - 0.25
    N-VA:
    - 0.15
    - 0.05
palette:
  Groen: tab:green
  'CD&V': blue
  Ecolo: tab:green
  MR: navy
  PS: tab:pink
  PVDA-PTB: red
  SP.A: tab:purple
  VB: orangered
  'Open Vld': magenta
  N-VA: tab:brown
