attitudinal:
  antielite_salience_vs_environment:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower right
    limits:
    - -2
    - 12
    nudges: &id001
      DLF:
      - -0.8
      - 0.5
      EELV:
      - 0.5
      - -0.5
      FI:
      - 0.5
      - 0.5
      LR:
      - 0.5
      - 0.5
      LREM:
      - 0.5
      - 0.5
      MoDem:
      - -0.5
      - -0.5
      PCF:
      - -0.5
      - -0.5
      PS:
      - 0.5
      - 0.5
      RN:
      - 0.7
      - -0.5
    quantiles: &id002
    - 0
    - 1
  antielite_salience_vs_eu_position:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower right
    limits:
    - -2
    - 12
    nudges: *id001
    quantiles: *id002
  antielite_salience_vs_galtan:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower right
    limits:
    - -2
    - 12
    nudges: *id001
    quantiles: *id002
  antielite_salience_vs_immigrate_policy:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower right
    limits:
    - -2
    - 12
    nudges: *id001
    quantiles: *id002
  eu_position_vs_environment:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower right
    limits:
    - -2
    - 12
    nudges: *id001
    quantiles: *id002
  eu_position_vs_galtan:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower right
    limits:
    - -2
    - 12
    nudges: *id001
    quantiles: *id002
  eu_position_vs_immigrate_policy:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower right
    limits:
    - -2
    - 12
    nudges: *id001
    quantiles: *id002
  galtan_vs_environment:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower right
    limits:
    - -2
    - 12
    nudges: *id001
    quantiles: *id002
  immigrate_policy_vs_environment:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower right
    limits:
    - -2
    - 12
    nudges: *id001
    quantiles: *id002
  immigrate_policy_vs_galtan:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower right
    limits:
    - -2
    - 12
    nudges: *id001
    quantiles: *id002
  lrecon_vs_antielite_salience:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower right
    limits:
    - -2
    - 12
    nudges: *id001
    quantiles: *id002
  lrecon_vs_environment:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower right
    limits:
    - -2
    - 12
    nudges: *id001
    quantiles: *id002
  lrecon_vs_eu_position:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower right
    limits:
    - -2
    - 12
    nudges: *id001
    quantiles: *id002
  lrecon_vs_galtan:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower right
    limits:
    - -2
    - 12
    nudges: *id001
    quantiles: *id002
  lrecon_vs_immigrate_policy:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower right
    limits:
    - -2
    - 12
    nudges: *id001
    quantiles: *id002
  lrgen_vs_antielite_salience:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    quantiles:
    - 0.01
    - 0.99
    legend_loc: lower right
    limits:
    - -2
    - 12
    nudges: *id001
    quantiles: *id002
  lrgen_vs_environment:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower right
    limits:
    - -2
    - 12
    nudges: *id001
    quantiles: *id002
  lrgen_vs_eu_position:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: upper right
    limits:
    - -2
    - 12
    nudges: *id001
    quantiles: *id002
  lrgen_vs_galtan:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower right
    limits:
    - -2
    - 12
    nudges: *id001
    quantiles: *id002
  lrgen_vs_immigrate_policy:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower right
    limits:
    - -2
    - 12
    nudges: *id001
    quantiles: *id002
  lrgen_vs_lrecon:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower right
    limits:
    - -2
    - 12
    nudges: *id001
    quantiles: *id002
ideological:
  cbar_rect:
  - 0.15
  - 0.3
  - 0.05
  - 0.5
  legend_loc: upper right
  limits:
    x:
    - -3.5
    - 3.5
    y:
    - -3.5
    - 3.5
  nudges:
    DLF:
    - -0.4
    - 0.2
    EELV:
    - 0
    - -0.7
    FI:
    - 0
    - 0.5
    LR:
    - 0.3
    - 0
    LREM:
    - 0
    - -0.7
    MoDem:
    - 0.35
    - -0.3
    PCF:
    - 0
    - 0.35
    PRG:
    - 0
    - 0
    PS:
    - 0
    - -0.6
    RN:
    - 0.3
    - -0.2
palette:
  DLF: gold
  EELV: tab:green
  FI: tab:purple
  LR: tab:blue
  LREM: tab:brown
  MoDem: orangered
  PCF: red
  PS: tab:pink
  RN: magenta
