attitudinal:
  ches2023:
    -
  gps2019:
    -
  ches2019:
    antielite_salience_vs_environment:
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        AfD:
        - -0.2
        - -0.45
        CDU:
        - -0.9
        - 0
        CSU:
        - -0.6
        - 0
        FDP:
        - 0.3
        - 0
        GRÜNE:
        - 0.4
        - -0.1
        LINKE:
        - 0.3
        - -0.1
        SPD:
        - 0.5
        - -0.1
    antielite_salience_vs_eu_position:
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        AfD:
        - -0.2
        - -0.45
        CDU:
        - -0.9
        - 0
        CSU:
        - -0.6
        - 0
        FDP:
        - 0.3
        - 0
        GRÜNE:
        - 0.4
        - -0.1
        LINKE:
        - 0.3
        - -0.1
        SPD:
        - 0.5
        - -0.1
    antielite_salience_vs_galtan:
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        AfD:
        - -0.2
        - -0.45
        CDU:
        - -0.9
        - 0
        CSU:
        - -0.6
        - 0
        FDP:
        - 0.3
        - 0
        GRÜNE:
        - 0.4
        - -0.1
        LINKE:
        - 0.3
        - -0.1
        SPD:
        - 0.5
        - -0.1
    antielite_salience_vs_immigrate_policy:
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        AfD:
        - -0.2
        - -0.45
        CDU:
        - -0.9
        - 0
        CSU:
        - -0.6
        - 0
        FDP:
        - 0.3
        - 0
        GRÜNE:
        - 0.4
        - -0.1
        LINKE:
        - 0.3
        - -0.1
        SPD:
        - 0.5
        - -0.1
    eu_position_vs_environment:
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        AfD:
        - -0.2
        - -0.45
        CDU:
        - -0.9
        - 0
        CSU:
        - -0.6
        - 0
        FDP:
        - 0.3
        - 0
        GRÜNE:
        - 0.4
        - -0.1
        LINKE:
        - 0.3
        - -0.1
        SPD:
        - 0.5
        - -0.1
    eu_position_vs_galtan:
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        AfD:
        - -0.2
        - -0.45
        CDU:
        - -0.9
        - 0
        CSU:
        - -0.6
        - 0
        FDP:
        - 0.3
        - 0
        GRÜNE:
        - 0.4
        - -0.1
        LINKE:
        - 0.3
        - -0.1
        SPD:
        - 0.5
        - -0.1
    eu_position_vs_immigrate_policy:
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        AfD:
        - -0.2
        - -0.45
        CDU:
        - -0.9
        - 0
        CSU:
        - -0.6
        - 0
        FDP:
        - 0.3
        - 0
        GRÜNE:
        - 0.4
        - -0.1
        LINKE:
        - 0.3
        - -0.1
        SPD:
        - 0.5
        - -0.1
    galtan_vs_environment:
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        AfD:
        - -0.2
        - -0.45
        CDU:
        - -0.9
        - 0
        CSU:
        - -0.6
        - 0
        FDP:
        - 0.3
        - 0
        GRÜNE:
        - 0.4
        - -0.1
        LINKE:
        - 0.3
        - -0.1
        SPD:
        - 0.5
        - -0.1
    immigrate_policy_vs_environment:
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        AfD:
        - -0.2
        - -0.45
        CDU:
        - -0.9
        - 0
        CSU:
        - -0.6
        - 0
        FDP:
        - 0.3
        - 0
        GRÜNE:
        - 0.4
        - -0.1
        LINKE:
        - 0.3
        - -0.1
        SPD:
        - 0.5
        - -0.1
    immigrate_policy_vs_galtan:
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        AfD:
        - -0.2
        - -0.45
        CDU:
        - -0.9
        - 0
        CSU:
        - -0.6
        - 0
        FDP:
        - 0.3
        - 0
        GRÜNE:
        - 0.4
        - -0.1
        LINKE:
        - 0.3
        - -0.1
        SPD:
        - 0.5
        - -0.1
    lrecon_vs_antielite_salience:
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        AfD:
        - -0.2
        - -0.45
        CDU:
        - -0.9
        - 0
        CSU:
        - -0.6
        - 0
        FDP:
        - 0.3
        - 0
        GRÜNE:
        - 0.4
        - -0.1
        LINKE:
        - 0.3
        - -0.1
        SPD:
        - 0.5
        - -0.1
    lrecon_vs_environment:
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        AfD:
        - -0.2
        - -0.45
        CDU:
        - -0.9
        - 0
        CSU:
        - -0.6
        - 0
        FDP:
        - 0.3
        - 0
        GRÜNE:
        - 0.4
        - -0.1
        LINKE:
        - 0.3
        - -0.1
        SPD:
        - 0.5
        - -0.1
    lrecon_vs_eu_position:
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        AfD:
        - -0.2
        - -0.45
        CDU:
        - -0.9
        - 0
        CSU:
        - -0.6
        - 0
        FDP:
        - 0.3
        - 0
        GRÜNE:
        - 0.4
        - -0.1
        LINKE:
        - 0.3
        - -0.1
        SPD:
        - 0.5
        - -0.1
    lrecon_vs_galtan:
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        AfD:
        - -0.2
        - -0.45
        CDU:
        - -0.9
        - 0
        CSU:
        - -0.6
        - 0
        FDP:
        - 0.3
        - 0
        GRÜNE:
        - 0.4
        - -0.1
        LINKE:
        - 0.3
        - -0.1
        SPD:
        - 0.5
        - -0.1
    lrecon_vs_immigrate_policy:
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        AfD:
        - -0.2
        - -0.45
        CDU:
        - -0.9
        - 0
        CSU:
        - -0.6
        - 0
        FDP:
        - 0.3
        - 0
        GRÜNE:
        - 0.4
        - -0.1
        LINKE:
        - 0.3
        - -0.1
        SPD:
        - 0.5
        - -0.1
    lrgen_vs_antielite_salience:
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        AfD:
        - -0.2
        - -0.45
        CDU:
        - -0.9
        - 0
        CSU:
        - -0.6
        - 0
        FDP:
        - 0.3
        - 0
        GRÜNE:
        - 0.4
        - -0.1
        LINKE:
        - 0.3
        - -0.1
        SPD:
        - 0.5
        - -0.1
    lrgen_vs_environment:
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        AfD:
        - -0.2
        - -0.45
        CDU:
        - -0.9
        - 0
        CSU:
        - -0.6
        - 0
        FDP:
        - 0.3
        - 0
        GRÜNE:
        - 0.4
        - -0.1
        LINKE:
        - 0.3
        - -0.1
        SPD:
        - 0.5
        - -0.1
    lrgen_vs_eu_position:
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        AfD:
        - -0.2
        - -0.45
        CDU:
        - -0.9
        - 0
        CSU:
        - -0.6
        - 0
        FDP:
        - 0.3
        - 0
        GRÜNE:
        - 0.4
        - -0.1
        LINKE:
        - 0.3
        - -0.1
        SPD:
        - 0.5
        - -0.1
    lrgen_vs_galtan:
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        AfD:
        - -0.2
        - -0.45
        CDU:
        - -0.9
        - 0
        CSU:
        - -0.6
        - 0
        FDP:
        - 0.3
        - 0
        GRÜNE:
        - 0.4
        - -0.1
        LINKE:
        - 0.3
        - -0.1
        SPD:
        - 0.5
        - -0.1
    lrgen_vs_immigrate_policy:
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        AfD:
        - -0.2
        - -0.45
        CDU:
        - -0.9
        - 0
        CSU:
        - -0.6
        - 0
        FDP:
        - 0.3
        - 0
        GRÜNE:
        - 0.4
        - -0.1
        LINKE:
        - 0.3
        - -0.1
        SPD:
        - 0.5
        - -0.1
    lrgen_vs_lrecon:
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        AfD:
        - -0.2
        - -0.45
        CDU:
        - -0.9
        - 0
        CSU:
        - -0.6
        - 0
        FDP:
        - 0.3
        - 0
        GRÜNE:
        - 0.4
        - -0.1
        LINKE:
        - 0.3
        - -0.1
        SPD:
        - 0.5
        - -0.1
ideological:
  cbar_rect:
  - 0.775
  - 0.55
  - 0.05
  - 0.35
  legend_loc: lower right
  limits:
    x:
    - -2
    - 3.5
    y:
    - -2
    - 3.5
  nudges:
    AfD:
    - -0.2
    - -0.45
    CDU:
    - -0.9
    - 0
    CSU:
    - -0.6
    - 0
    FDP:
    - 0.3
    - 0
    GRÜNE:
    - 0.4
    - -0.1
    LINKE:
    - 0.3
    - -0.1
    SPD:
    - 0.5
    - -0.1
palette:
  AfD: magenta
  CDU: black
  CSU: tab:blue
  FDP: gold
  GRÜNE: tab:green
  LINKE: mediumvioletred
  SPD: red
