attitudinal:
  antielite_salience_vs_environment: &id001
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower center
    limits:
    - -2
    - 12
    nudges:
      PNL:
      - 0.2
      - -0.2
      UDMR:
      - 0
      - 0.2
      PSD:
      - 0.2
      - 0.2
      USR:
      - 0.2
      - 0
  antielite_salience_vs_eu_position: *id001
  antielite_salience_vs_immigrate_policy: *id001
  eu_position_vs_environment: *id001
  eu_position_vs_immigrate_policy: *id001
  immigrate_policy_vs_environment: *id001
  lrecon_vs_antielite_salience: *id001
  lrecon_vs_environment: *id001
  lrecon_vs_eu_position: *id001
  lrecon_vs_immigrate_policy: *id001
  lrgen_vs_antielite_salience: *id001
  lrgen_vs_environment: *id001
  lrgen_vs_eu_position: *id001
  lrgen_vs_immigrate_policy: *id001
  lrgen_vs_lrecon: *id001
  lrgen_vs_galtan: &id002
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower center
    limits:
    - -6
    - 16
    nudges:
      PNL:
      - 0.4
      - 0.4
      UDMR:
      - 0.4
      - 0.4
      PSD:
      - 0.4
      - 0.4
      USR:
      - 0.4
      - 0.4
  galtan_vs_environment: *id002
  antielite_salience_vs_galtan: *id002
  eu_position_vs_galtan: *id002
  lrecon_vs_galtan: *id002
  immigrate_policy_vs_galtan: *id002
ideological:
  cbar_rect:
  - 0.15
  - 0.45
  - 0.03
  - 0.3
  legend_loc: upper right
  gridsize:
    - 200
    - 50
  limits:
    x:
    - -2
    - 2
    y:
    - -2
    - 3
  nudges:
    PNL:
    - 0.1
    - 0.1
    UDMR:
    - -0.5
    - 0.1
    PSD:
    - 0.15
    - -0.1
    USR:
    - 0.1
    - 0.1
palette:
  PNL: cornflowerblue
  UDMR: gold
  PSD: tab:purple
  USR: orangered
  AUR: black
  GPMN: black
  FD: black
  PLUS: black
  REPER: black
  PUSL: black
  AD: black
  ApP: black
  'S.O.S. România': black