attitudinal:
  gps2019:
    V4_Scale_vs_V6_Scale: &id002
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        -
    V4_Scale_vs_V8_Scale: *id002
    V4_Scale_vs_v9: *id002
    V4_Scale_vs_v10: *id002
    V4_Scale_vs_v12: *id002
    V4_Scale_vs_v13: *id002
    V4_Scale_vs_v14: *id002
    V4_Scale_vs_v18: *id002
    V4_Scale_vs_v19: *id002
    V4_Scale_vs_v20: *id002
    V4_Scale_vs_v21: *id002
  ches2019:
    antielite_salience_vs_environment: &id001
      cbar_rect:
      - 0.15
      - 0.6
      - 0.02
      - 0.3
      legend_loc: lower center
      limits:
      - -2
      - 12
      nudges:
        -
    antielite_salience_vs_eu_position: *id001
    antielite_salience_vs_galtan: *id001
    antielite_salience_vs_immigrate_policy: *id001
    eu_position_vs_environment: *id001
    eu_position_vs_galtan: *id001
    eu_position_vs_immigrate_policy: *id001
    galtan_vs_environment: *id001
    immigrate_policy_vs_environment: *id001
    immigrate_policy_vs_galtan: *id001
    lrecon_vs_antielite_salience: *id001
    lrecon_vs_environment: *id001
    lrecon_vs_eu_position: *id001
    lrecon_vs_galtan: *id001
    lrecon_vs_immigrate_policy: *id001
    lrgen_vs_antielite_salience: *id001
    lrgen_vs_environment: *id001
    lrgen_vs_eu_position: *id001
    lrgen_vs_galtan: *id001
    lrgen_vs_immigrate_policy: *id001
    lrgen_vs_lrecon: *id001
ideological:
  cbar_rect:
  - 0.175
  - 0.45
  - 0.03
  - 0.45
  legend_loc: upper right
  limits:
    x:
    - -1.5
    - 2.5
    y:
    - -1
    - 3
  nudges:
    SAB:
    - 0.2
    - -0.2
    DeSUS:
    - 0
    - 0.2
    LMS:
    - 0.2
    - 0.2
    Levica:
    - 0.2
    - 0
    NSI:
    - 0
    - -0.4
    SD:
    - -0.2
    - -0.4
    SDS:
    - -0.5
    - -0.2
    SMC:
    - 0.2
    - -0.25
    SNS:
    - 0
    - 0.2
palette:
  SAB: magenta
  DeSUS: cornflowerblue
  LMS: gold
  Levica: red
  NSI: tab:pink
  SD: tab:purple
  SDS: mediumvioletred
  SMC: orangered
  SNS: tab:green
