attitudinal:
  gps2019:
    -
  ches2019:
    - 
ideological:
  cbar_rect:
  - 0.175
  - 0.45
  - 0.03
  - 0.45
  legend_loc: upper right
  limits:
    x:
    - -1.5
    - 2.5
    y:
    - -1
    - 3
  nudges:
    SAB:
    - 0.2
    - -0.2
    DeSUS:
    - 0
    - 0.2
    LMS:
    - 0.2
    - 0.2
    Levica:
    - 0.2
    - 0
    NSI:
    - 0
    - -0.4
    SD:
    - -0.2
    - -0.4
    SDS:
    - -0.5
    - -0.2
    SMC:
    - 0.2
    - -0.25
    SNS:
    - 0
    - 0.2
palette:
  SAB: magenta
  DeSUS: cornflowerblue
  LMS: gold
  Levica: red
  NSI: tab:pink
  SD: tab:purple
  SDS: mediumvioletred
  SMC: orangered
  SNS: tab:green
