attitudinal:
  antielite_salience_vs_environment:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower center
    limits:
    - -2
    - 12
    nudges:
      BNG:
      - 0.2
      - -0.5
      CC:
      - 0
      - -0.8
      Cs:
      - 0
      - -0.8
      EHB:
      - 0.2
      - -0.2
      ERC:
      - 0.2
      - -0.2
      PNV:
      - 0.25
      - -0.4
      PPP:
      - 0.4
      - 0
      PSOE:
      - 0.35
      - 0
      Pais:
      - 0.25
      - 0.1
      Podemos:
      - -1.2
      - 0.3
      Vox:
      - 0
      - -0.7
  antielite_salience_vs_eu_position:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower center
    limits:
    - -2
    - 12
    nudges:
      BNG:
      - 0.2
      - -0.5
      CC:
      - 0
      - -0.8
      Cs:
      - 0
      - -0.8
      EHB:
      - 0.2
      - -0.2
      ERC:
      - 0.2
      - -0.2
      PNV:
      - 0.25
      - -0.4
      PPP:
      - 0.4
      - 0
      PSOE:
      - 0.35
      - 0
      Pais:
      - 0.25
      - 0.1
      Podemos:
      - -1.2
      - 0.3
      Vox:
      - 0
      - -0.7
  antielite_salience_vs_galtan:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower center
    limits:
    - -2
    - 12
    nudges:
      BNG:
      - 0.2
      - -0.5
      CC:
      - 0
      - -0.8
      Cs:
      - 0
      - -0.8
      EHB:
      - 0.2
      - -0.2
      ERC:
      - 0.2
      - -0.2
      PNV:
      - 0.25
      - -0.4
      PPP:
      - 0.4
      - 0
      PSOE:
      - 0.35
      - 0
      Pais:
      - 0.25
      - 0.1
      Podemos:
      - -1.2
      - 0.3
      Vox:
      - 0
      - -0.7
  antielite_salience_vs_immigrate_policy:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower center
    limits:
    - -2
    - 12
    nudges:
      BNG:
      - 0.2
      - -0.5
      CC:
      - 0
      - -0.8
      Cs:
      - 0
      - -0.8
      EHB:
      - 0.2
      - -0.2
      ERC:
      - 0.2
      - -0.2
      PNV:
      - 0.25
      - -0.4
      PPP:
      - 0.4
      - 0
      PSOE:
      - 0.35
      - 0
      Pais:
      - 0.25
      - 0.1
      Podemos:
      - -1.2
      - 0.3
      Vox:
      - 0
      - -0.7
  eu_position_vs_environment:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower center
    limits:
    - -2
    - 12
    nudges:
      BNG:
      - 0.2
      - -0.5
      CC:
      - 0
      - -0.8
      Cs:
      - 0
      - -0.8
      EHB:
      - 0.2
      - -0.2
      ERC:
      - 0.2
      - -0.2
      PNV:
      - 0.25
      - -0.4
      PPP:
      - 0.4
      - 0
      PSOE:
      - 0.35
      - 0
      Pais:
      - 0.25
      - 0.1
      Podemos:
      - -1.2
      - 0.3
      Vox:
      - 0
      - -0.7
  eu_position_vs_galtan:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower center
    limits:
    - -2
    - 12
    nudges:
      BNG:
      - 0.2
      - -0.5
      CC:
      - 0
      - -0.8
      Cs:
      - 0
      - -0.8
      EHB:
      - 0.2
      - -0.2
      ERC:
      - 0.2
      - -0.2
      PNV:
      - 0.25
      - -0.4
      PPP:
      - 0.4
      - 0
      PSOE:
      - 0.35
      - 0
      Pais:
      - 0.25
      - 0.1
      Podemos:
      - -1.2
      - 0.3
      Vox:
      - 0
      - -0.7
  eu_position_vs_immigrate_policy:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower center
    limits:
    - -2
    - 12
    nudges:
      BNG:
      - 0.2
      - -0.5
      CC:
      - 0
      - -0.8
      Cs:
      - 0
      - -0.8
      EHB:
      - 0.2
      - -0.2
      ERC:
      - 0.2
      - -0.2
      PNV:
      - 0.25
      - -0.4
      PPP:
      - 0.4
      - 0
      PSOE:
      - 0.35
      - 0
      Pais:
      - 0.25
      - 0.1
      Podemos:
      - -1.2
      - 0.3
      Vox:
      - 0
      - -0.7
  galtan_vs_environment:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower center
    limits:
    - -2
    - 12
    nudges:
      BNG:
      - 0.2
      - -0.5
      CC:
      - 0
      - -0.8
      Cs:
      - 0
      - -0.8
      EHB:
      - 0.2
      - -0.2
      ERC:
      - 0.2
      - -0.2
      PNV:
      - 0.25
      - -0.4
      PPP:
      - 0.4
      - 0
      PSOE:
      - 0.35
      - 0
      Pais:
      - 0.25
      - 0.1
      Podemos:
      - -1.2
      - 0.3
      Vox:
      - 0
      - -0.7
  immigrate_policy_vs_environment:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower center
    limits:
    - -2
    - 12
    nudges:
      BNG:
      - 0.2
      - -0.5
      CC:
      - 0
      - -0.8
      Cs:
      - 0
      - -0.8
      EHB:
      - 0.2
      - -0.2
      ERC:
      - 0.2
      - -0.2
      PNV:
      - 0.25
      - -0.4
      PPP:
      - 0.4
      - 0
      PSOE:
      - 0.35
      - 0
      Pais:
      - 0.25
      - 0.1
      Podemos:
      - -1.2
      - 0.3
      Vox:
      - 0
      - -0.7
  immigrate_policy_vs_galtan:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower center
    limits:
    - -2
    - 12
    nudges:
      BNG:
      - 0.2
      - -0.5
      CC:
      - 0
      - -0.8
      Cs:
      - 0
      - -0.8
      EHB:
      - 0.2
      - -0.2
      ERC:
      - 0.2
      - -0.2
      PNV:
      - 0.25
      - -0.4
      PPP:
      - 0.4
      - 0
      PSOE:
      - 0.35
      - 0
      Pais:
      - 0.25
      - 0.1
      Podemos:
      - -1.2
      - 0.3
      Vox:
      - 0
      - -0.7
  lrecon_vs_antielite_salience:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower center
    limits:
    - -2
    - 12
    nudges:
      BNG:
      - 0.2
      - -0.5
      CC:
      - 0
      - -0.8
      Cs:
      - 0
      - -0.8
      EHB:
      - 0.2
      - -0.2
      ERC:
      - 0.2
      - -0.2
      PNV:
      - 0.25
      - -0.4
      PPP:
      - 0.4
      - 0
      PSOE:
      - 0.35
      - 0
      Pais:
      - 0.25
      - 0.1
      Podemos:
      - -1.2
      - 0.3
      Vox:
      - 0
      - -0.7
  lrecon_vs_environment:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower center
    limits:
    - -2
    - 12
    nudges:
      BNG:
      - 0.2
      - -0.5
      CC:
      - 0
      - -0.8
      Cs:
      - 0
      - -0.8
      EHB:
      - 0.2
      - -0.2
      ERC:
      - 0.2
      - -0.2
      PNV:
      - 0.25
      - -0.4
      PPP:
      - 0.4
      - 0
      PSOE:
      - 0.35
      - 0
      Pais:
      - 0.25
      - 0.1
      Podemos:
      - -1.2
      - 0.3
      Vox:
      - 0
      - -0.7
  lrecon_vs_eu_position:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower center
    limits:
    - -2
    - 12
    nudges:
      BNG:
      - 0.2
      - -0.5
      CC:
      - 0
      - -0.8
      Cs:
      - 0
      - -0.8
      EHB:
      - 0.2
      - -0.2
      ERC:
      - 0.2
      - -0.2
      PNV:
      - 0.25
      - -0.4
      PPP:
      - 0.4
      - 0
      PSOE:
      - 0.35
      - 0
      Pais:
      - 0.25
      - 0.1
      Podemos:
      - -1.2
      - 0.3
      Vox:
      - 0
      - -0.7
  lrecon_vs_galtan:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower center
    limits:
    - -2
    - 12
    nudges:
      BNG:
      - 0.2
      - -0.5
      CC:
      - 0
      - -0.8
      Cs:
      - 0
      - -0.8
      EHB:
      - 0.2
      - -0.2
      ERC:
      - 0.2
      - -0.2
      PNV:
      - 0.25
      - -0.4
      PPP:
      - 0.4
      - 0
      PSOE:
      - 0.35
      - 0
      Pais:
      - 0.25
      - 0.1
      Podemos:
      - -1.2
      - 0.3
      Vox:
      - 0
      - -0.7
  lrecon_vs_immigrate_policy:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower center
    limits:
    - -2
    - 12
    nudges:
      BNG:
      - 0.2
      - -0.5
      CC:
      - 0
      - -0.8
      Cs:
      - 0
      - -0.8
      EHB:
      - 0.2
      - -0.2
      ERC:
      - 0.2
      - -0.2
      PNV:
      - 0.25
      - -0.4
      PPP:
      - 0.4
      - 0
      PSOE:
      - 0.35
      - 0
      Pais:
      - 0.25
      - 0.1
      Podemos:
      - -1.2
      - 0.3
      Vox:
      - 0
      - -0.7
  lrgen_vs_antielite_salience:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower center
    limits:
    - -2
    - 12
    nudges:
      BNG:
      - 0.2
      - -0.5
      CC:
      - 0
      - -0.8
      Cs:
      - 0
      - -0.8
      EHB:
      - 0.2
      - -0.2
      ERC:
      - 0.2
      - -0.2
      PNV:
      - 0.25
      - -0.4
      PPP:
      - 0.4
      - 0
      PSOE:
      - 0.35
      - 0
      Pais:
      - 0.25
      - 0.1
      Podemos:
      - -1.2
      - 0.3
      Vox:
      - 0
      - -0.7
  lrgen_vs_environment:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower center
    limits:
    - -2
    - 12
    nudges:
      BNG:
      - 0.2
      - -0.5
      CC:
      - 0
      - -0.8
      Cs:
      - 0
      - -0.8
      EHB:
      - 0.2
      - -0.2
      ERC:
      - 0.2
      - -0.2
      PNV:
      - 0.25
      - -0.4
      PPP:
      - 0.4
      - 0
      PSOE:
      - 0.35
      - 0
      Pais:
      - 0.25
      - 0.1
      Podemos:
      - -1.2
      - 0.3
      Vox:
      - 0
      - -0.7
  lrgen_vs_eu_position:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower center
    limits:
    - -2
    - 12
    nudges:
      BNG:
      - 0.2
      - -0.5
      CC:
      - 0
      - -0.8
      Cs:
      - 0
      - -0.8
      EHB:
      - 0.2
      - -0.2
      ERC:
      - 0.2
      - -0.2
      PNV:
      - 0.25
      - -0.4
      PPP:
      - 0.4
      - 0
      PSOE:
      - 0.35
      - 0
      Pais:
      - 0.25
      - 0.1
      Podemos:
      - -1.2
      - 0.3
      Vox:
      - 0
      - -0.7
  lrgen_vs_galtan:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower center
    limits:
    - -2
    - 12
    nudges:
      BNG:
      - 0.2
      - -0.5
      CC:
      - 0
      - -0.8
      Cs:
      - 0
      - -0.8
      EHB:
      - 0.2
      - -0.2
      ERC:
      - 0.2
      - -0.2
      PNV:
      - 0.25
      - -0.4
      PPP:
      - 0.4
      - 0
      PSOE:
      - 0.35
      - 0
      Pais:
      - 0.25
      - 0.1
      Podemos:
      - -1.2
      - 0.3
      Vox:
      - 0
      - -0.7
  lrgen_vs_immigrate_policy:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower center
    limits:
    - -2
    - 12
    nudges:
      BNG:
      - 0.2
      - -0.5
      CC:
      - 0
      - -0.8
      Cs:
      - 0
      - -0.8
      EHB:
      - 0.2
      - -0.2
      ERC:
      - 0.2
      - -0.2
      PNV:
      - 0.25
      - -0.4
      PPP:
      - 0.4
      - 0
      PSOE:
      - 0.35
      - 0
      Pais:
      - 0.25
      - 0.1
      Podemos:
      - -1.2
      - 0.3
      Vox:
      - 0
      - -0.7
  lrgen_vs_lrecon:
    cbar_rect:
    - 0.15
    - 0.6
    - 0.02
    - 0.3
    legend_loc: lower center
    limits:
    - -2
    - 12
    nudges:
      BNG:
      - 0.2
      - -0.5
      CC:
      - 0
      - -0.8
      Cs:
      - 0
      - -0.8
      EHB:
      - 0.2
      - -0.2
      ERC:
      - 0.2
      - -0.2
      PNV:
      - 0.25
      - -0.4
      PPP:
      - 0.4
      - 0
      PSOE:
      - 0.35
      - 0
      Pais:
      - 0.25
      - 0.1
      Podemos:
      - -1.2
      - 0.3
      Vox:
      - 0
      - -0.7
ideological:
  cbar_rect:
  - 0.15
  - 0.4
  - 0.05
  - 0.5
  legend_loc: lower right
  limits:
    x:
    - -4
    - 2
    y:
    - -4
    - 2
  nudges:
    BNG:
    - 0.2
    - -0.5
    CC:
    - 0
    - -0.8
    Cs:
    - 0
    - -0.8
    EHB:
    - 0.2
    - -0.2
    ERC:
    - 0.2
    - -0.2
    PNV:
    - 0.25
    - -0.4
    PPP:
    - 0.4
    - 0
    PSOE:
    - 0.35
    - 0
    Pais:
    - 0.25
    - 0.1
    Podemos:
    - -1.2
    - 0.3
    Vox:
    - 0
    - -0.7
palette:
  BNG: tab:brown
  CC: purple
  Cs: orangered
  EHB: mediumvioletred
  ERC: gold
  PNV: tab:green
  PPP: tab:blue
  PSOE: red
  Pais: tab:pink
  Podemos: tab:purple
  Vox: magenta
