attitudinal_dimensions:
  gps2019:
    - V4_Scale
    - V6_Scale
    - V8_Scale
    - v9
    - v10
    - v12
    - v13
    - v14
    - v18
    - v19
    - v20
    - v21
  ches2019:
    - lrgen
    - lrecon
    - eu_position
    - antielite_salience
    - immigrate_policy
    - galtan
    - environment
    - enviro_salience
    - nationalism
    - sociallifestyle
    - people_vs_elite
    - corrupt_salience
  ches2023:
    - lrecon
    - refugees
    - EU_Russia
    - eu_position
    - galtan
    - UA_EU
    - energy_costs
    - weapons
    - supportUA
    - antielite_salience
    - Kremlin_ties
ideological_model:
  check_input: true
  engine: auto
  force_bipartite: true
  force_full_rank: false
  in_degree_threshold: 3
  out_degree_threshold: null
  random_state: null
  standardize_mean: true
  standardize_std: false
sources_min_followers: 25
sources_min_outdegree: 3
params_db: /home/jimena/work/dev/some4demDB/config.yml
sqlite_db: '/home/jimena/work/data/some4dem/dbs/{country}.db'
export_folder: '/home/jimena/work/dev/some4demEmbeddings/exports/deliverableD21'
validation:
  seed: 666