countries = {
    'Australia':{'languages':['en'],'marpor2020_countryname':'Australia'},
    'Austria':{'languages':['de'],'ches2019_country':'aus','marpor2020_countryname':'Austria'},
    'Belgium':{'languages':['de','fr','nl'],'ches2019_country':'be','marpor2020_countryname':'Belgium'},
    'Canada':{'languages':['en','fr'],'marpor2020_countryname':'Canada'},
    'Denmark':{'languages':['da','de',],'ches2019_country':'dk','marpor2020_countryname':'Denmark'},
    'EuropeanParliament':{'languages':['ca', 'en', 'es', 'el', 'el-Latn', 'eu', 'de', 'fi', 'fr', 'ga', 'gl', 'is', 'it', 'lv', 'lb', 'nl', 'no', 'pl', 'pt', 'sv', 'sl', 'tr']},
    'Finland':{'languages':['fi','sv'],'ches2019_country':'fin','marpor2020_countryname':'Finland'},
    'France':{'languages':['fr'],'ches2019_country':'fr','marpor2020_countryname':'France'},
    'Germany':{'languages':['de'],'ches2019_country':'ge','marpor2020_countryname':'Germany'},
    'Greece':{'languages':['el','el-Latn'],'ches2019_country':'gr','marpor2020_countryname':'Greece'},
    'Iceland':{'languages':['is'],'ches2019_country':'ice','marpor2020_countryname':'Iceland'},
    'Ireland':{'languages':['en','ga'],'ches2019_country':'irl','marpor2020_countryname':'Ireland'},
    'Italy':{'languages':['it'],'ches2019_country':'it','marpor2020_countryname':'Italy'},
    'Latvia':{'languages':['lv'],'ches2019_country':'lat','marpor2020_countryname':'Latvia'},
    'Luxembourg':{'languages':['fr','de','lb'],'ches2019_country':'lux','marpor2020_countryname':'Luxembourg'},
    'Malta':{'languages':['mt','en','it'],'ches2019_country':'mal','marpor2020_countryname':'Malta'},
    'Netherlands':{'languages':['nl','en'],'ches2019_country':'nl','marpor2020_countryname':'Netherlands'},
    'NewZealand':{'languages':['en'],'marpor2020_countryname':'New Zealand'},
    'Norway':{'languages':['no'],'ches2019_country':'nor','marpor2020_countryname':'Norway'},
    'Poland':{'languages':['pl'],'ches2019_country':'pol','marpor2020_countryname':'Poland'},
    'Slovenia':{'languages':['sl'],'ches2019_country':'sle','marpor2020_countryname':'Slovenia'},
    'Spain':{'languages':['es','ca','eu','gl'],'ches2019_country':'esp','marpor2020_countryname':'Spain'},
    'Sweden':{'languages':['sv'],'ches2019_country':'sv','marpor2020_countryname':'Sweden'},
    'Switzerland':{'languages':['it','fr','de'],'ches2019_country':'swi','marpor2020_countryname':'Switzerland'},
    'Turkey':{'languages':['tr'],'ches2019_country':'tur','marpor2020_countryname':'Turkey'},
    'UnitedKingdom':{'languages':['en'],'ches2019_country':'uk','marpor2020_countryname':'United Kingdom'},
    'UnitedStates':{'languages':['en'],'marpor2020_countryname':'United States'},  
    # Own collection
    'AustriaOwn':{'languages':['de'],'ches2019_country':'aus','marpor2020_countryname':'Austria'},
    'BrazilOwn':{'languages':['pt'],'marporLA2020_countryname':'Brazil'},
    'ChileOwn':{'languages':['es'],'marporLA2020_countryname':'Chile'},
    'FranceOwn':{'languages':['fr'],'ches2019_country':'fr','marpor2020_countryname':'France'},
    'GermanyOwn':{'languages':['de'],'ches2019_country':'ge','marpor2020_countryname':'Germany'},
    'ItalyOwn':{'languages':['it'],'ches2019_country':'it','marpor2020_countryname':'Italy'},
    'UKOwn':{'languages':['en'],'ches2019_country':'uk','marpor2020_countryname':'United Kingdom'},
    'USOwn':{'languages':['en'],'marpor2020_countryname':'United States'},
    }